server:
  port: 8888

spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: C:\Workspaces\Telefonica\MicroserviciosAwi\awi-config-repository
          default-label: master